#!/usr/bin/env Rscript
# =============================================================================
# gen_adam_labels.R -- derive the ADaM variable-label artifacts for BOTH tracks
# from the AUTHORITATIVE spec (00_specifications/ADaM_spec.xlsx), so the SAS
# production track and the R validation track carry identical, SPEC-sourced
# labels:
#   * 03_validation_r/adam_var_labels.csv  -- read by config_study.R (R track)
#   * 02_production_sas/_adam_labels.sas    -- %lbl_<ds> macros %included by
#                                              U_xpt_export.sas (SAS track)
#
# This REPLACES the previous 06_telemetry/gen_adam_labels.py, which sourced the
# same artifacts FROM define.xml. The spec is now the single source of truth and
# define.xml is checked against it (audit C-4 inversion). Regenerate after
# editing the spec:   Rscript 06_telemetry/gen_adam_labels.R
# =============================================================================

suppressMessages({
  library(metacore)
  library(dplyr)
})
.find_file <- function(rel) {
  cands <- c(
    rel, file.path("..", rel),
    file.path(Sys.getenv("TROPIC_ROOT", "."), rel)
  )
  hit <- Filter(file.exists, cands)
  if (!length(hit)) stop("cannot locate ", rel, " from ", getwd())
  normalizePath(hit[[1]])
}
source(.find_file("03_validation_r/load_spec.R"))

spec <- load_tropic_spec()
ds_order <- spec$ds_spec$dataset

# variable-level (dataset, variable, label) in spec order, non-empty labels only
labs <- bind_rows(lapply(ds_order, function(ds) {
  s <- suppressMessages(select_dataset(spec, ds))
  s$ds_vars %>%
    left_join(s$var_spec, by = "variable") %>%
    arrange(order) %>%
    transmute(dataset = ds, variable, label) %>%
    filter(!is.na(label) & nzchar(trimws(label)))
}))

# ----------------------------------------------------------------- CSV (R) -----
# Minimally-quoted, CRLF line endings to match the historical (python csv) format
# exactly -- so the only change vs the retired generator is provenance, not bytes.
csv_out <- "03_validation_r/adam_var_labels.csv"
csv_lines <- "dataset,variable,label"
for (i in seq_len(nrow(labs))) {
  lab <- labs$label[i]
  lab <- if (grepl('[",]', lab)) paste0('"', gsub('"', '""', lab), '"') else lab
  csv_lines <- c(csv_lines, paste(labs$dataset[i], labs$variable[i], lab, sep = ","))
}
con <- file(csv_out, open = "wb", encoding = "UTF-8")
writeLines(csv_lines, con, sep = "\r\n")
close(con)

# --------------------------------------------------------------- SAS macros ----
sas_out <- "02_production_sas/_adam_labels.sas"
lines <- c(
  "/* Program:     _adam_labels.sas",
  "   Description: ADaM variable-label macros (%lbl_<ds>) applied in U_xpt_export.sas before XPT export.",
  "                GENERATED by 06_telemetry/gen_adam_labels.R from 00_specifications/ADaM_spec.xlsx.",
  "                Do not edit by hand. */",
  ""
)
for (ds in ds_order) {
  d <- labs %>% filter(dataset == ds)
  lines <- c(lines, sprintf("%%macro lbl_%s;", tolower(ds)), "  label")
  for (i in seq_len(nrow(d))) {
    esc <- gsub("'", "''", d$label[i]) # double apostrophes for SAS literal
    lines <- c(lines, sprintf("    %s = '%s'", d$variable[i], esc))
  }
  lines <- c(lines, "  ;", sprintf("%%mend lbl_%s;", tolower(ds)), "")
}
lines <- lines[seq_len(max(which(nzchar(lines))))] # drop trailing blank line
writeLines(lines, sas_out, useBytes = TRUE)

cat(sprintf(
  "Wrote %d labels -> %s (%d datasets) and %s\n",
  nrow(labs), csv_out, length(ds_order), sas_out
))
