#!/usr/bin/env python3
"""gen_adam_labels.py — derive the ADaM variable-label spec from define.xml and emit it for BOTH
tracks, so production (SAS) and validation (R) datasets carry identical, define-sourced labels:

  * 03_validation_r/adam_var_labels.csv   — read by config_study.R::write_xpt_v (R track)
  * 02_production_sas/_adam_labels.sas     — %lbl_<ds> macros %included by U_xpt_export.sas (SAS track)

Regenerate whenever define.xml labels change:  python3 06_telemetry/gen_adam_labels.py
"""
import csv, json, os, subprocess, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, ".."))
META = os.path.join(HERE, "adam_conf_define_meta.json")
CSV_OUT = os.path.join(ROOT, "03_validation_r", "adam_var_labels.csv")
SAS_OUT = os.path.join(ROOT, "02_production_sas", "_adam_labels.sas")

# refresh the flattened define metadata first
subprocess.run([sys.executable, os.path.join(HERE, "adam_conf_parse_define.py")], check=True)
meta = json.load(open(META, encoding="utf-8"))

rows = []
for ds, info in meta["datasets"].items():
    for v in info["variables"]:
        lab = (v["label"] or "").strip()
        if lab:
            rows.append((ds, v["name"], lab))

with open(CSV_OUT, "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f)
    w.writerow(["dataset", "variable", "label"])
    w.writerows(rows)

# SAS: one %lbl_<ds> macro per dataset; single-quoted (no macro resolution), apostrophes doubled.
lines = ["/* _adam_labels.sas — GENERATED by 06_telemetry/gen_adam_labels.py from define.xml.",
         "   Do not edit by hand. %lbl_<ds> applied in U_xpt_export.sas before XPT export. */", ""]
for ds, info in meta["datasets"].items():
    lines.append(f"%macro lbl_{ds.lower()};")
    lines.append("  label")
    for v in info["variables"]:
        lab = (v["label"] or "").strip()
        if lab:
            lines.append(f"    {v['name']} = '{lab.replace(chr(39), chr(39)*2)}'")
    lines.append("  ;")
    lines.append(f"%mend lbl_{ds.lower()};")
    lines.append("")
open(SAS_OUT, "w", encoding="utf-8").write("\n".join(lines))

print(f"[gen] {len(rows)} labels -> {os.path.relpath(CSV_OUT, ROOT)} + {os.path.relpath(SAS_OUT, ROOT)}")
