import xml.etree.ElementTree as ET
import pandas as pd
import os
from pathlib import Path

# Audit C-4: this script RENDERS define.xml into a human-readable workbook for reviewers.
# It is explicitly NOT the upstream "specification" - generating a spec from the define it is
# meant to govern would be a circular (zero-verification) traceability inversion. The output is
# therefore named an "extract" and carries a provenance sheet. The authoritative spec->define
# direction (a metacore-style single-source-of-truth spec that GENERATES define) is on the roadmap.
def generate_specs():
    project_root = Path(__file__).parent.parent
    define_path = project_root / '07_define_xml' / 'define.xml'
    output_dir = project_root / '00_specifications'
    output_dir.mkdir(exist_ok=True)
    output_file = output_dir / 'ADaM_Define_Extract.xlsx'
    
    if not define_path.exists():
        print(f"Define.xml not found at {define_path}")
        return

    # Namespaces
    ns = {
        'odm': 'http://www.cdisc.org/ns/odm/v1.3',
        'def': 'http://www.cdisc.org/ns/def/v2.1'
    }

    tree = ET.parse(define_path)
    root = tree.getroot()

    datasets = []
    variables = []

    # Parse ItemGroupDefs (Datasets)
    for ig in root.findall('.//odm:ItemGroupDef', ns):
        ds_name = ig.attrib.get('Name')
        purpose = ig.attrib.get('Purpose', '')
        structure = ig.attrib.get('def:Structure', '')
        
        desc_node = ig.find('.//odm:Description/odm:TranslatedText', ns)
        description = desc_node.text if desc_node is not None else ''

        datasets.append({
            'Dataset': ds_name,
            'Description': description,
            'Structure': structure,
            'Purpose': purpose
        })

        # Parse ItemRefs (Variables within Dataset)
        for ir in ig.findall('odm:ItemRef', ns):
            item_oid = ir.attrib.get('ItemOID')
            order = ir.attrib.get('OrderNumber', '')
            mandatory = ir.attrib.get('Mandatory', '')
            
            # Find the corresponding ItemDef
            item_def = root.find(f'.//odm:ItemDef[@OID="{item_oid}"]', ns)
            if item_def is not None:
                var_name = item_def.attrib.get('Name')
                data_type = item_def.attrib.get('DataType')
                length = item_def.attrib.get('Length', '')
                
                label_node = item_def.find('.//odm:Description/odm:TranslatedText', ns)
                label = label_node.text if label_node is not None else ''
                
                origin_node = item_def.find('.//def:Origin', ns)
                origin_type = origin_node.attrib.get('Type') if origin_node is not None else ''
                origin_desc_node = item_def.find('.//def:Origin/odm:Description/odm:TranslatedText', ns)
                origin_desc = origin_desc_node.text if origin_desc_node is not None else ''

                variables.append({
                    'Dataset': ds_name,
                    'Variable': var_name,
                    'Label': label,
                    'Type': data_type,
                    'Length': length,
                    'Order': int(order) if order else 999,
                    'Mandatory': mandatory,
                    'Origin': origin_type,
                    'Derivation/Source': origin_desc
                })

    df_ds = pd.DataFrame(datasets)
    df_vars = pd.DataFrame(variables).sort_values(by=['Dataset', 'Order'])

    # Provenance banner so no reader mistakes this rendering for a governing specification.
    df_prov = pd.DataFrame({
        'Field': ['Artifact', 'Provenance', 'Direction', 'Authoritative source', 'Generated by'],
        'Value': [
            'ADaM Define-XML Extract (reviewer-facing, human-readable rendering)',
            f'Derived FROM {define_path.name} - NOT an independent specification',
            'define.xml -> this workbook (a VIEW). This is NOT spec -> define.',
            '07_define_xml/define.xml (CDISC Define-XML 2.1 + ARM, XSD-validated)',
            '06_telemetry/generate_adam_specs.py',
        ],
    })

    # Write to Excel
    with pd.ExcelWriter(output_file, engine='openpyxl') as writer:
        df_prov.to_excel(writer, sheet_name='_Provenance', index=False)
        df_ds.to_excel(writer, sheet_name='Datasets', index=False)
        df_vars.to_excel(writer, sheet_name='Variables', index=False)
        
        # Adjust column widths (basic formatting)
        for sheet_name in writer.sheets:
            worksheet = writer.sheets[sheet_name]
            for col in worksheet.columns:
                max_length = 0
                column = col[0].column_letter # Get the column name
                for cell in col:
                    if cell.value is not None:
                        max_length = max(max_length, len(str(cell.value)))
                adjusted_width = (max_length + 2)
                worksheet.column_dimensions[column].width = min(adjusted_width, 60)

    print(f"Successfully generated ADaM Define-XML extract at: {output_file}")

if __name__ == "__main__":
    generate_specs()
