# Program: cross_lang_audit.R | Version: 2.0 | Author: Clinical Data Architect | Date: 2026-05-23
# Description: Cross-Language cell-by-cell validation audit comparing SAS (*_prod.xpt) and R (*_val.xpt).

library(haven)
library(dplyr)
library(diffdf)

cat("NOTE: [RECONCILIATION] Starting Cross-Language Audit...\n")

compare_datasets <- function(ds_name) {
  prod_path <- paste0("04_adam/", ds_name, "_prod.xpt")
  val_path <- paste0("04_adam/", ds_name, "_v.xpt")
  
  if (!file.exists(prod_path) || !file.exists(val_path)) {
    return(list(status = "FAIL", reason = "Missing production or validation XPT file"))
  }
  
  prod <- read_xpt(prod_path)
  val <- read_xpt(val_path)
  
  # Standardize column casing
  colnames(prod) <- toupper(colnames(prod))
  colnames(val) <- toupper(colnames(val))
  
  # Column symmetry check (QC-02)
  prod_cols <- colnames(prod)
  val_cols <- colnames(val)
  extra_in_prod <- setdiff(prod_cols, val_cols)
  extra_in_val <- setdiff(val_cols, prod_cols)
  
  if (length(extra_in_prod) > 0 || length(extra_in_val) > 0) {
    reason_parts <- c()
    if (length(extra_in_prod) > 0) {
      reason_parts <- c(reason_parts, paste("Extra in Prod:", paste(extra_in_prod, collapse = ", ")))
    }
    if (length(extra_in_val) > 0) {
      reason_parts <- c(reason_parts, paste("Extra in Val:", paste(extra_in_val, collapse = ", ")))
    }
    return(list(status = "FAIL", reason = paste("Column mismatch -", paste(reason_parts, collapse = "; "))))
  }
  
  # Align business keys based on dataset name (QC-01)
  if (ds_name == "adsl") {
    sort_keys <- "USUBJID"
  } else if (ds_name == "adex") {
    sort_keys <- c("USUBJID", "PARAMCD", "AVISIT")
  } else if (ds_name == "adcm") {
    sort_keys <- c("USUBJID", "CMSTDT", "CMDECOD")
  } else if (ds_name == "adae") {
    sort_keys <- c("USUBJID", "ASTDT", "AEDECOD")
  } else if (ds_name == "adlb") {
    sort_keys <- c("USUBJID", "PARAMCD", "AVISITN", "LBDY")
  } else if (ds_name == "adrs") {
    sort_keys <- c("USUBJID", "PARAMCD", "AVISIT")
  } else if (ds_name == "adtte") {
    sort_keys <- c("USUBJID", "PARAMCD")
  }
  
  # Align column classes & types first to ensure clean sorting
  common_cols <- intersect(colnames(prod), colnames(val))
  for (col in common_cols) {
    p_col <- prod[[col]]
    v_col <- val[[col]]
    
    # Handle factor/character mismatch
    if (is.character(p_col) || is.factor(p_col)) {
      prod[[col]] <- as.character(p_col)
      val[[col]]  <- as.character(v_col)
    }
    
    # Coerce missing representations (empty strings to NA)
    if (is.character(prod[[col]])) {
      prod[[col]][is.na(prod[[col]]) | prod[[col]] == ""] <- NA_character_
      val[[col]][is.na(val[[col]]) | val[[col]] == ""]   <- NA_character_
    }
  }
  
  # Sort by business keys, then by all other columns to guarantee deterministic row order
  other_cols <- setdiff(common_cols, sort_keys)
  prod <- prod %>% arrange(across(all_of(c(sort_keys, other_cols))))
  val  <- val  %>% arrange(across(all_of(c(sort_keys, other_cols))))
  
  # Add ROW_ID as the unique key for diffdf cell-by-cell comparison
  prod$ROW_ID <- 1:nrow(prod)
  val$ROW_ID  <- 1:nrow(val)
  keys <- "ROW_ID"
  
  # Compare using diffdf package
  diff_res <- diffdf(prod, val, keys = keys, suppress_warnings = TRUE)
  
  if (!diffdf_has_issues(diff_res)) {
    return(list(status = "PASS", reason = "Zero cell-level differences"))
  } else {
    # Extract details of differences
    val_diffs <- attr(diff_res, "ValueDiffs")
    total_diffs <- 0
    if (!is.null(val_diffs)) {
      for (col_name in names(val_diffs)) {
        col_diff <- val_diffs[[col_name]]
        n_mismatches <- nrow(col_diff)
        total_diffs <- total_diffs + n_mismatches
        cat(paste("  [MISMATCH] Column", col_name, "has", n_mismatches, "cell differences (diffdf audit).\n"))
      }
    } else {
      # Fallback if there are row mismatches, class mismatches etc.
      total_diffs <- 1
    }
    return(list(status = "FAIL", reason = paste(total_diffs, "cell differences found")))
  }
}

datasets <- c("adsl", "adex", "adcm", "adae", "adlb", "adrs", "adtte")
results <- list()

for (ds in datasets) {
  res <- compare_datasets(ds)
  results[[ds]] <- res
  cat(paste("NOTE: [RECONCILIATION] Dataset:", toupper(ds), "-", res$status, "-", res$reason, "\n"))
}

# Determine if simulation mode is active
is_simulated <- Sys.getenv("TROPIC_SAS_SIMULATION") == "TRUE" || Sys.which("sas") == ""

banner_html <- ""
if (is_simulated) {
  banner_html <- paste0(
    "<div style='background-color: #fff3cd; color: #856404; border: 1px solid #ffeeba; ",
    "padding: 15px; border-radius: 5px; margin-bottom: 20px; font-weight: bold;'>",
    "⚠️ WARNING: Simulated SAS compilation was used. Production datasets (*_prod.xpt) ",
    "were generated by copying the R validation datasets rather than executing a real SAS engine. ",
    "Zero differences are expected and do not guarantee independent double-programming parity on a SAS engine.",
    "</div>"
  )
}

# Generate visual HTML report
html_content <- paste0(
  "<html><head><title>TROPIC Cross-Language Reconciliation Report</title>",
  "<style>body { font-family: 'Segoe UI', Arial, sans-serif; background-color: #f8f9fa; color: #333; margin: 40px; }",
  "h1 { color: #002d62; } .card { background: white; padding: 20px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.1); }",
  "table { width: 100%; border-collapse: collapse; margin-top: 20px; } th, td { padding: 12px; border-bottom: 1px solid #ddd; text-align: left; }",
  "th { background-color: #002d62; color: white; } .pass { color: green; font-weight: bold; } .fail { color: red; font-weight: bold; }</style></head>",
  "<body><div class='card'><h1>TROPIC (Study EFC6193 / XRP6258) Cross-Language Audit Dashboard</h1>",
  banner_html,
  "<p>Cell-by-cell validation report comparing SAS 9.4 Production models vs R 4.5.2 Pharmaverse Validation Track.</p>",
  "<table><thead><tr><th>Dataset</th><th>Status</th><th>Audit Details</th></tr></thead><tbody>"
)

for (ds in datasets) {
  res <- results[[ds]]
  status_class <- if (res$status == "PASS") "pass" else "fail"
  html_content <- paste0(
    html_content,
    "<tr><td><strong>", toupper(ds), "</strong></td><td class='", status_class, "'>", res$status, "</td><td>", res$reason, "</td></tr>"
  )
}

html_content <- paste0(html_content, "</tbody></table></div></body></html>")

dir.create("06_telemetry", showWarnings = FALSE)
writeLines(html_content, "06_telemetry/reconciliation_report.html")
cat("NOTE: [RECONCILIATION] Visual HTML audit saved to 06_telemetry/reconciliation_report.html\n")
